app/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'some-secret-key'

    from app.routes.routes import blueprint

    app.register_blueprint(blueprint)

    app.config['SECRET_KEY'] = 'some-secret-key'

    return app

app/routes/routes.py
import os
import ast
import json
import requests
from app.api.spotify_handler import SpotifyHandler
from app.api.spotify_client import SpotifyClient
from flask import render_template, Blueprint, request, redirect, url_for, session

blueprint = Blueprint('app', __name__)

client_id = os.environ.get('CLIENT_ID')
client_secret = os.environ.get('CLIENT_SECRET')


spotify_client = SpotifyClient(client_id, client_secret, port=8002)
spotify_handler = SpotifyHandler()


@blueprint.route("/login", methods=['POST', 'GET'])
def login():
    # Auth Step 1: Authorization
    auth_url = spotify_client.get_auth_url()
    return redirect(auth_url)


@blueprint.route("/callback/q")
def callback():
    # Requests refresh and access tokens
    auth_token = request.args['code']
    spotify_client.get_authorization(auth_token)
    authorization_header = spotify_client._authorization_header
    session['authorization_header'] = authorization_header
    return redirect(url_for("app.select_tracks"))


@blueprint.route("/select-tracks", methods=['GET', 'POST'])
def select_tracks():
    if request.method == 'GET':
        return render_template('loading.html')


@blueprint.route("/load", methods=['GET', 'POST'])
def load():
    authorization_header = session['authorization_header']
    extract_letters = lambda x: ''.join([letter for letter in x if not letter.isdigit()])

    if request.method == 'GET':
        # -------- Get user's name, id, and set session --------
        profile_data = spotify_handler.get_user_profile_data(authorization_header)
        user_display_name, user_id = profile_data['display_name'], profile_data['id']
        session['user_id'], session['user_display_name'] = user_id, user_display_name

        # -------- Get user playlist data --------
        playlist_data = spotify_handler.get_user_playlist_data(authorization_header, user_id)

        return render_template('select.html',
                               user_display_name=user_display_name,
                               playlists_data=playlist_data,
                               func=extract_letters)

    return render_template('404.html')


@blueprint.route("/finetune", methods=['GET', 'POST'])
def finetune():
    selected_tracks = request.form.get('selected_tracks').split(',')
    session['selected_tracks'] = selected_tracks
    return render_template('finetune.html')


@blueprint.route("/your-playlist", methods=['GET', 'POST'])
def your_playlist():
    authorization_header = session['authorization_header']
    fine_tune_vals = json.loads(f"[{request.form.get('fine-tune-values')}]")
    fine_tune_vals = [{val['key']: val['val'] for val in fine_tune_vals}][0]

    if request.method == 'POST':
        params = {
            'seed_tracks': session['selected_tracks'],
            'danceability': float(fine_tune_vals['danceability']) / 10,
            'energy': float(fine_tune_vals['energy']) / 10,
            'loudness': -60 + (float(fine_tune_vals['loudness']) - 1) * 60 / 9,
            'popularity': int(fine_tune_vals['popularity']) * 10
        }

        get_reccomended_url = f"https://api.spotify.com/v1/recommendations?limit={25}"
        response = requests.get(get_reccomended_url, headers=authorization_header, params=params).text
        tracks = list(json.loads(response)['tracks'])
        tracks_uri = [track['uri'] for track in tracks]
        session['tracks_uri'] = tracks_uri

        return render_template('result.html', data=tracks)

    return redirect(url_for('not_found'))


@blueprint.route("/save-playlist", methods=['GET', 'POST'])
def save_playlist():
    authorization_header = session['authorization_header']
    user_id = session['user_id']

    playlist_name = request.form.get('playlist_name')
    playlist_data = json.dumps({
        "name": playlist_name,
        "description": "Recommended songs",
        "public": True
    })
    create_playlist_url = f"https://api.spotify.com/v1/users/{user_id}/playlists"
    response = requests.post(create_playlist_url, headers=authorization_header, data=playlist_data).text
    playlist_id = json.loads(response)['id']

    tracks_uri = session['traks_uri']
    tracks_data = json.dumps({
        "uris": tracks_uri,
    })
    add_items_url = f"https://api.spotify.com/v1/playlists/{playlist_id}/tracks"
    response = requests.post(add_items_url, headers=authorization_header, data=tracks_data).text

    return render_template('listen.html', playlist_id=playlist_id)


@blueprint.route("/")
def main():
    return render_template('main.html')


@blueprint.route("/not-found")
def not_found():
    return render_template('404.html')


@blueprint.route("/listen")
def listen():
    return render_template('listen.html')


@blueprint.route("/refresh", methods=['GET', 'POST'])
def refresh_result():
    return redirect(url_for("app.your_playlist"))

app/templates/base.html
<!DOCTYPE html>
<html lang="eng">

    <head>
        <meta charset="utf-8">
        <title>Spotify Playlist Generator</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Signika">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/untitled-1.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/untitled.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-slider.css') }}">

    </head>

    <body>
        <h1>Spotify Playlist Generator</h1>

        {% block content %}
        {% endblock %}

        {#        <p class="text-center d-xl-flex align-items-xl-start" id="made-by">Made by <a#}
        {#                href="https://github.com/AcrobaticPanicc/">&nbsp;Tomer</a>.</p>#}

        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                crossorigin="anonymous"></script>

        <script src="../static/js/main.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="../static/js/bootstrap-slider.js"></script>


    </body>

</html>

app/templates/finetune.html
{% extends "base.html" %} {% block content %}

<body class="text-break" style="background-image: linear-gradient(50deg, #2c5e92 0%, #2d784c 80%);">
    <div class="container text-center hi">
        <h2 class="main-p">
            <p>Great selection!</p>
            Now, let's fine tune the results
        </h2>
    </div>

    <div class="danceability attribute">
        <div class="container text-center hi">
            <p>How DANCEABLE the playlist should be?</p>
            <h6 class="greyed">1-Not danceable <span>|</span> 10-Very danceable</h6>
            <span class="side-numbers">1</span>
            <label>
                <input class="input-values" id="danceability" type="text" data-provide="slider" data-slider-min="0" data-slider-max="10" data-slider-step="1" data-slider-value="0" />
            </label>
            <span class="side-numbers">10</span>
        </div>
    </div>

    <hr />

    <div class="energy attribute">
        <div class="container text-center hi">
            <p>How much ENERGY the playlist should have?</p>
            <h6 class="greyed">1-Not energetic <span>|</span> 10-Full power</h6>
            <span class="side-numbers">1</span>
            <label>
                <input class="input-values" id="energy" type="text" data-provide="slider" data-slider-min="0" data-slider-max="10" data-slider-step="1" data-slider-value="0" />
            </label>
            <span class="side-numbers">10</span>
        </div>
    </div>

    <hr />

    <div class="loudness attribute">
        <div class="container text-center hi">
            <p>How LOUD the playlist should be?</p>
            <h6 class="greyed">1-Quiet <span>|</span> 10-LOUD</h6>
            <span class="side-numbers">1</span>
            <label>
                <input class="input-values" id="loudness" type="text" data-provide="slider" data-slider-min="1" data-slider-max="10" data-slider-step="1" data-slider-value="0" />
            </label>
            <span class="side-numbers">10</span>
        </div>
    </div>

    <hr />

    <div class="popularity attribute">
        <div class="container text-center hi">
            <p>How POPULAR the tracks in the playlist should be?</p>
            <h6 class="greyed">1-Not popular <span>|</span> 10-Very popular</h6>

            <span class="side-numbers">1</span>
            <label>
                <input class="input-values" id="popularity" type="text" data-provide="slider" data-slider-min="0" data-slider-max="10" data-slider-step="1" data-slider-value="0" />
            </label>
            <span class="side-numbers">10</span>
        </div>
    </div>

    <hr/>

    <div class="text-center next-btn-div">
        <form action="/your-playlist" method="POST">
            <input type="hidden" id="tune-values" name="fine-tune-values" value=""/>
            <a>
                <button class="btn next-btn btn-primary" value="submit" id="login-btn" type="submit" onclick="getFineTune()">
                    Next
                </button>
            </a>
        </form>
    </div>
</body>

{% endblock %}

app/templates/listen.html
{% extends "base.html" %}
{% block content %}


    <body class="text-break">

        <div class="container text-center">
            <p>Listen to your new playlist </p>
        </div>

        <div class="text-center" style="text-align: center;margin: 17px 20% 50px;">
            <iframe src="https://open.spotify.com/embed/playlist/{{ playlist_id }}" width="300" height="380"
                    frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>

        <div class="text-center" style="padding-top: 47px;">
            <a href="/">Go back home</a>
        </div>

        <script>
            window.onSpotifyWebPlaybackSDKReady = () => {
                // You can now initialize Spotify.Player and use the SDK
            };
        </script>
        <script src="https://sdk.scdn.co/spotify-player.js"></script>
    </body>


{% endblock %}

app/templates/loading.html
{% extends "base.html" %}
{% block content %}


    <body class="text-break">
        <div class="container text-center hi ">
            <p class="main-p">Please wait, we are getting your playlists information</p>
            <div class="container text-center hi">
                <img id="loading-gif" src="../static/images/spinner.gif" alt="">
            </div>
        </div>
    </body>


        <script type="text/javascript">
            $.ajax({
                type: 'POST',
                url: '/load',
                success: function () {
                    window.location.replace('/load');
                }
            });
        </script>

{% endblock %}

app/templates/main.html
{% extends "base.html" %}
{% block content %}


    <body>
        <div class="container text-center hi">
            <p class="main-p">
                Discover new music by creating a custom Spotify playlist based on your favourite tracks<br>
            </p>
        </div>

        <div class="text-center" style="padding-top: 47px;">
            <a href="{{ url_for('app.login') }}">
                <button class="btn btn-primary" id="login-btn" type="button">
                    Log in with Spotify
                </button>
            </a>

        </div>
        <p class="greyed">
            *We are using Spotify's secure login to connect to your account.<br>
        </p>


    </body>

{% endblock %}

app/templates/result.html
{% extends "base.html" %}
{% block content %}


    <body class="text-break">
        <h1 id="done">
            DONE! 👏
        </h1>

        <div class="container text-center">
            <p>This is the new playlist we created for you based on your selected tracks and preferences</p>
        </div>

        <ul class="list-group">
            {% for track in data %}
                {% set track_id = track["id"] %}
                {% set artist_name = track["artists"][0]["name"] %}
                {% set track_name = track["name"] %}
                {% set track_image_url = track["album"]["images"][2]["url"] %}

                <li class="list-group-item list-group-item d-flex justify-content-between align-items-center track"
                    value="{{ track_id }}">
                    <span>{{ artist_name }} - {{ track_name }}</span>
                    <div>
                        <img src="{{ track_image_url }}" style="max-width: 47px;" alt="">
                    </div>
                </li>
            {% endfor %}
        </ul>

        <div>
            <p class="text-center text-white">Give a name to your new playlist:</p>
        </div>

        <div class="text-center"
             style="text-align: center;margin: 17px 20% 50px;">
            <form action="/save-playlist" method="POST">
                <div class="text-center">
                    <input type="text" id="playlist_name" name="playlist_name" value="">
                </div>
                <button class="btn btn-primary" id="login-btn" type="submit">
                    Save playlist
                </button>
            </form>
        </div>


        <div>
            <form action="/refresh" method="post">
                <p class="text-center text-white not-happy">
                    Not happy with this playlist?
                    <span>
                    <a href="/refresh">
                        Get a new one!
                    </a>
                </span>
                </p>
            </form>
        </div>
    </body>


{% endblock %}

app/templates/select.html
{% extends "base.html" %}
{% block content %}

    <body class="text-break" style="background-image: linear-gradient(50deg, #2c5e92 0%, #2d784c 80%);">

        <div class="container text-center hi">
            <p style="font-size: 40px;">
                Hi {{ user_display_name }}!
            </p>

            <p>
                Here are your playlists on Spotify.<br>Click on a playlist and select the tracks you want to base your
                recommendation on
            </p>
        </div>


        <ul class="list-group">
            {% for playlist in playlists_data %}
                {% set playlist_id = playlist['playlist_id'] %}
                {% set playlist_name = playlist['playlist_name'] %}
                {% set playlist_url = playlist['playlist_url'] %}
                {% set playlist_img_url = playlist['playlist_img_url'] %}
                {% set tracks = playlist['playlist_tracks'] %}

                <li data-toggle="collapse" href="#{{ func(playlist_id) }}" data-target="#{{ func(playlist_id) }}"
                    class="list-group-item list-group-item d-flex justify-content-between align-items-center playlists">
                    <span>{{ playlist_name }}</span>
                    <div>
                        <img src="{{ playlist_img_url }}" style="max-width: 47px;" alt="">
                    </div>
                </li>

                <div class="collapse" id="{{ func(playlist_id) }}">
                    <ul>
                        {% for track in  tracks %}
                            <li class="list-group-item list-group-item d-flex justify-content-between align-items-center track"
                                value="{{ track['track_id'] }}" onclick="addSelectedClass(this)">
                                <span>{{ track['track_artist'] }} - {{ track['track_name'] }}</span>
                                <div>
                                    <img src="{{ track['track_image'] }}" style="max-width: 47px;" alt="">
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </ul>


        <div class="text-center next-btn-div">
            <form action="/finetune" method="POST">
                <input type="hidden" id="selected_tracks" name="selected_tracks" value="">
                <a>
                    <button class="btn next-btn btn-primary" value="submit" id="login-btn" type="submit"
                            onclick="getTracks()">
                        Next
                    </button>
                </a>
            </form>
        </div>
    </body>



{% endblock %}